# Generated by Django 4.1.7 on 2023-02-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_useraccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_avatar.png', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
    ]
