# Generated by Django 4.1.7 on 2023-02-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='contact_details',
            field=models.CharField(blank=True, help_text='You can mention contact number, email id or social handels here.', max_length=200, null=True, verbose_name='Contact Details'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='description',
            field=models.TextField(blank=True, help_text='Description will help others to know more about you/organization.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraccount'),
        ),
        migrations.DeleteModel(
            name='PublisherAccount',
        ),
    ]
